# Render Blueprint - Kanji Master
# Deploy cả Frontend + Backend + Socket.IO trên 1 service

services:
  - type: web
    name: kanji-master
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://rum_db_user:Ntd158683@cluster0.uqqhwbg.mongodb.net/kanji_master?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
